### ISSUE TITLE
Number of arguments mismatch

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#125]
Hello,

When compiling AliceO2 with FairRoot there is a mismatch found in the call of the function:

FairMQTransportFactory::CreateMessage(void* data, const size_t size, fairmq_free_fn* ffn, void* hint = NULL)

from the source file: 

devices/flp2epn-distributed/FLPSender.cxx

where only the first two arguments are specified. In my local fix I have added the NULL default 
argument for the third one too and succeeded to compile till the end.

Thanks you for looking on this.

cheers,

Bogdan.

**Comment by rbx** [comment]
Hi,

this is fixed in the dev branch. You are probably using the master branch, which is meanwhile 6 months old.
Adding NULL as the third argument would create a memory leak when running that device, so if you want to run that device, take a look at proper way in Examples/flp2epn-distributed/FLPSender.cxx in the dev branch. But since a lot has changed in that file in 6 months, I'd recommend switching to the dev branch.

**Comment by bovulpes** [comment]
Ok, thanks, I must have missed the "-b dev" in the readme.

Bogdan.
