### ISSUE TITLE
Pull request verification fails with unrelated error

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#246]
Jenkins is failing on PR verification, but the error is not related to the PR
```
DEBUG:O2:0: [ 29%] Generating G__FieldDict.cxx, G__FieldDict_rdict.pcm, ../../lib/libField.rootmap
DEBUG:O2:0: [ 29%] Linking CXX shared library ../../../lib/libQCMetricsExtractor.so
DEBUG:O2:0: input_line_12:152:10: fatal error: 'Pythia.h' file not found
DEBUG:O2:0: #include "Pythia.h"  // for Pythia
DEBUG:O2:0:          ^
DEBUG:O2:0: Error: /build/workarea/pr/2460/3/slc7_x86-64/ROOT/v6-08-02-1/bin/rootcint: compilation failure (/build/workarea/pr/2460/3/BUILD/dea1caeced1f8a1f2c0499d669fb4149d72a99b4/O2/Generators/G__GeneratorsDict0e692f09d4_dictUmbrella.h)
DEBUG:O2:0: make[2]: *** [Generators/G__GeneratorsDict.cxx] Error 1
DEBUG:O2:0: make[1]: *** [Generators/CMakeFiles/Generators.dir/all] Error 2
DEBUG:O2:0: make[1]: *** Waiting for unfinished jobs....
```

More details for #245 in https://alijenkins.cern.ch/job/aliceo2-pipeline/job/PR-245/1/console

**Comment by shahor02** [comment]
Hello,
The problem is created by a38bba73b720f597fa8198d7d58478d900ad1492 :
in Generators/include/Generators/Pythia8Generator.h
-#include "Pythia8/Pythia.h"  // for Pythia
+#include "Pythia.h"  // for Pythia

The dictionary is generated with  ``-I/home/shahoian/alice/sw/ubuntu1604_x86-64/pythia/v8211pre-1/include`` while the Pythia.h is in ``/home/shahoian/alice/sw/ubuntu1604_x86-64/pythia/v8211pre-1/include/Pythia8``. @MohammadAlTurany , it seems the O2Dependencies.cmake should be modified but I don't know how.

Cheers,
 Ruben

**Comment by sawenzel** [comment]
Indeed commit a38bba7 is the problem here plus the fact that o2.sh recipe sets PYTHIA8_INCLUDE_DIR to 
 `${PYTHIA_ROOT:+-DPYTHIA8_INCLUDE_DIR=$PYTHIA_ROOT/include}`.  This is a clear contradiction.

Since this is a blocker for the PR tests now, I am in favour of going back to `include "Pythia8/Pythia.h"`.

**Comment by sawenzel** [comment]
See PR #252.

Another argument to stick with "Pythia8/Pythia.h" is the fact that the Pythia.h header itself uses this convention. So we should really have "$PYTHIA_ROOT/include" as include dir otherwise Pythia.h will not find its sub-headers.
