### ISSUE TITLE
Clarification/improvement of INCLUDE_DIR component in buckets

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/AliceO2#250]
```
o2_define_bucket(
   NAME
   Foo

   DEPENDENCIES
   Bar
   Base
   RIO

   INCLUDE_DIRECTORIES
   BarHeaders
)
```

I am slightly confused about the semantics of the INCLUDE_DIRECTORIES field in the bucket definitions. It seems that this field is rarely  needed when compiling modules/libraries. However, I noticed that we need to put information for `BarHeaders` for the purpose of ROOT dictionary generation **even though** `Bar` is already listed as dependencies.

Hence, a suggestion for improvement would be to automatically include the "INC_DIRS" of dependencies everywhere and only use `INCLUDE_DIRECTORIES` for things not listed in the `DEPENDENCIES`.

**Comment by matthiasrichter** [comment]
I did some investigation regarding this issue. If the dependency is a bucket, also all the (system)include directories are recursively retrieved in `GET_BUCKET_CONTENT` and added to the includes of a module.

Another case is probably if the dependency is a library from a different module of the same project. Like e.g. the `Field` module/library which is a dependency for `tpc_simulation_bucket`. Here also the include
path is added explicitly in the `INCLUDE` section. I suppose this is exactly for the reason of this issue.

However, removing the path from the include does not have any effect on the dictionary generation, it is generated without problems.

Maybe this issue is solved, what do you think @sawenzel ?

Side remark: What is not yet clear to me is how the include path of another internal module which has been specified as dependency makes it to the list of include directories. There are only three occurrences of `target_include_directories` in `O2Utils.txt`, but none of them seems to do this. Maybe some cmake magic connected to `target_link_libraries` when the dependencies are known internally.

**Comment by Barthelemy** [comment]
@matthiasrichter 
Concerning the side remark : yes, as far as I know, it is some CMake magic that works when dependencies are built and known internally.

**Comment by sawenzel** [comment]
@matthiasrichter : Thanks for the explanation. This means that we might be able to cleanup our bucket definitions quite a lot.

**Comment by ktf** [comment]
Closing this as I understand this is understood. Feel free to reopen if not the case.
