### ISSUE TITLE
.clang-format does not work with default centos7 clang 3.4

### ISSUE THREAD

**Issue by mkrzewic** [AliceO2Group/AliceO2#261]
Hi, the .clang-format file provided with the dev branch of O2 assumes clang 3.9 - so it will work on mac probably, but does not work on centos7 (clang 3.4). Can we revert to the older version by default?

**Comment by sawenzel** [comment]
There are multiple easy ways to get clang3.9 + clang-format:
a) alibuild build clang (and hopefully being able to just fetch a prebuild binary)
b) take it from afs or cernvmfs (lcg releases)

I would be in disfavour of going back with the version, in particular since we need clang3.9 for 
the static code analysis.

**Comment by mkrzewic** [comment]
@sawenzel no luck getting a prebuilt version, i'm running the build. Can clang3.9 be added to --defaults-o2 so we consistently get it?

**Comment by Barthelemy** [comment]
we should really have a way to get prebuilt packages from alibuild, especially for stuff like clang. @ktf ?

I think that we can add clang 3.9 to the defaults for o2. What matters is that it does not get built by default, only if explicitely asked.

**Comment by sawenzel** [comment]
I think we can close this issue. clang3.9 is available through our recipes or through /cvmfs/sft.cern.ch/lcg/..
