### ISSUE TITLE
Build fails in pythia6 (on Mac)

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#314]
> aliBuild --defaults o2 build O2

ends with : 

==> Building pythia6@428_O2
==> pythia6 is being built (use --debug for full output): failed
ERROR: Error while executing /Users/laurent/alice/tmp/sw/SPECS/osx_x86-64/pythia6/428_O2-1/build.sh on `nanpc420.local'.
ERROR: Log can be found in /Users/laurent/alice/tmp/sw/BUILD/pythia6-latest/log.
ERROR: Please attach this file if you intend to request support.
ERROR: Build directory is /Users/laurent/alice/tmp/sw/BUILD/pythia6-latest/pythia6

[log.txt](https://github.com/AliceO2Group/AliceO2/files/903333/log.txt)

❯ alibuild version
aliBuild version: 1.4.0

❯ uname -a
Darwin nanpc420.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

**Comment by sawenzel** [comment]
It fails at linking stage. Probably we need to point the compiler to the right gfortran lib.

**Comment by sawenzel** [comment]
The missing symbols are indeed all in the standard `gfortran` lib.
Do you have this lib installed? What is the output of `which gfortran`?

If you have a fortran installation, you may possibly try to modify the pythia6 recipe

in

`https://github.com/alisw/pythia6/blob/alice/428/CMakeLists.txt`

and try adding (something like)

`target_link_library(pythia6 gfortran)`

@dberzano: What is your opinion?

**Comment by mfasDa** [comment]
I can confirm this problem. I added the line Sandro suggests to my private fork of pythia6 in order to be able to compile. See: https://github.com/mfasDa/pythia6/tree/alice/428 . In principle this can be pulled into master.

In addition I ran into a second build failure, this time on Ubuntu 16.04, in LHAPDF, in the configure stage, dealing with a bug in the boost.m4 for autoconf. The bug was fixed upstream, an there is a pull request open for this https://github.com/alisw/LHAPDF/pull/1

I would appreciate very much if the two issues would get solved (pull requests merged).

**Comment by sawenzel** [comment]
@mfasDa: very good. I think these problems should be linked/duplicated in the alidist repo. @dberzano : What do you think?

**Comment by sawenzel** [comment]
@mfasDa : I opened a PR from your branch into alisw/pythia6. Please follow up the other issue independently.

**Comment by dberzano** [comment]
Adding @qgp to the loop, he's taking care of this part.

**Comment by dr4kan** [comment]
I get the same error too. Any news on this?
@mfasDa Can you please elaborate on which CMakeLists you modified in order to make the code compile? Thanks.
