### ISSUE TITLE
Constructor of o2::Header::DataDescription should pad with 0, not " " 

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#372]
Right now we have that:

```
o2::Header::DataDescription::DataDescription("CLUSTERS") != gDataDescriptionClusters
```

because gDataDescriptionClusters is right-padded with spaces. I would suggest that either:

* The constructor pads with spaces rather than spaces.
* `gDataDescriptionClusters` and alikes are 0 padded (preferred).

**Comment by mkrzewic** [comment]
agree on the second point - should be zero padded.
Another point is that the ctor should never explicitly be used in code - i'm working on a more consistent handling of that - the only (public) ctor will be copy ctor. Initialization with the strings etc. will be special and most probably only allowed in special definition files, otherwise we will run into this class of problems - we need the semantics of strongly typed enums here, but with more features than "enum class" provides - hence the special handling. i'll try to prepare a PR ASAP.

**Comment by ktf** [comment]
We do need a runtime way of creating headers and therefore data descriptions, though. If anything else to test things. At the moment I am resorting to something like:

```C++
o2::Header::DataDescription o2::Header::lookupDataDescription(const char *key) {
  if (strcmp(key, "RAWDATA") == 0)
    return o2::Header::gDataDescriptionRawData;
  else if (strcmp(key, "CLUSTERS") == 0)
    return o2::Header::gDataDescriptionClusters;
  else if (strcmp(key, "TRACKS") == 0)
    return o2::Header::gDataDescriptionTracks;
  else if (strcmp(key, "CONFIG") == 0)
    return o2::Header::gDataDescriptionConfig;
  else if (strcmp(key, "INFO") == 0)
    return o2::Header::gDataDescriptionInfo;
  return o2::Header::gDataDescriptionInvalid;
}
```

while I am not suggesting this should be the implementation, we do need something with the same semantic.

**Comment by ktf** [comment]
Rewording the issue to match the agreement.

**Comment by matthiasrichter** [comment]
At the moment the constructor does '0' padding, but the inequality in the initial post comes from the definition
https://github.com/AliceO2Group/AliceO2/blob/4852caeb570d0143545ebc9f3b873440bbd048c7/DataFormats/Headers/src/DataHeader.cxx#L39

```bash
const o2::Header::DataDescription o2::Header::gDataDescriptionClusters("CLUSTERS       ");
```
Actually I would keep the '0' padding, this is also what I read in the comments. That's why the title of the issue confuses me.

For the runtime part I did something similar for the `Descriptor` struct (which is unfortunately only up to 64bit) by adding the method `runtimeInit(const char* string)`, for exactly the same reasoning.

**Comment by matthiasrichter** [comment]
Just a follow up, the `runtimeInit` method is available for both the `DataDescription` and the `Descriptor`-derivatives, I had added them together at the same time.

**Comment by matthiasrichter** [comment]
How do we conclude here? I vote for leaving the constructor as it as, it pads with '0'. Then the definitions can be changed to e.g.

```bash
const o2::Header::DataDescription o2::Header::gDataDescriptionClusters("CLUSTERS");
```
without blanks.

Or would that conflict with the new implementation?

**Comment by ktf** [comment]
+1
